display_name: Helios
package_name: helios
maintainer:
  name: Martin Jindra
  email: martin@mjindra.eu
priority: optional
section: x11
installed_size: 7021892
essential: false
icon: assets/logo.png
dependencies:
  - zenity

keywords:
  - Helios
  - DnD
  - Aurora
  - character builder

generic_name: Helios

categories:
  - Utility

startup_notify: true