app_id: 4G5K3908-42B3-4234-A479-BC079F21A12F
publisher: Martin Jindra
publisher_url: https://github.com/MartinJindra/Helios
display_name: Helios
create_desktop_icon: true
install_dir_name: helios
locales:
  - en
  - de
